### ISSUE TITLE
Package quicksect not installing correctly

### ISSUE THREAD

**Issue by angus-lherrou** [jianlins/quicksectx#4]
I believe #3 has not been fully resolved.

### Problems

When installed from source, the ValueError from #3 still occurs:

```
$ pip install --no-cache-dir --no-binary quicksectx quicksectx                                                                                                                                                                   
Collecting quicksectx
  Downloading quicksectx-0.3.1.tar.gz (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 kB 4.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9p/6n96dp9x27v28xcq81fk2rjm0000gn/T/pip-install-jh0my93i/quicksectx_e47ce7cf143747acba72abee52194f10/setup.py", line 53, in <module>
          ext_modules=cythonize(extensions, compiler_directives={'language_level': "3"}),
        File "/Users/stygg/miniforge3/envs/kw38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/Users/stygg/miniforge3/envs/kw38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/Users/stygg/miniforge3/envs/kw38/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'quicksect/quicksect.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

When installed from a wheel, the package for traditional quicksect (`import quicksect`) does not get installed properly when quicksectx is installed:

```python
>>> import quicksectx
>>> import quicksect
>>> dir(quicksectx)
['Interval', 'IntervalNode', 'IntervalTree', '__builtins__', '__cached__', 
'__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', 
'__spec__', '__version__', 'distancex', 'quicksectx', 'unicode_literals', 'version']
>>> dir(quicksect)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>> quicksectx.Interval
<class 'quicksectx.quicksectx.Interval'>
>>> quicksect.Interval
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'quicksect' has no attribute 'Interval'
```

The module's contents are still accessible under `quicksect.quicksect`, however:

```python
>>> import quicksect.quicksect
>>> quicksect.quicksect.Interval
<class 'quicksect.quicksect.Interval'>
```

I believe this is due to `quicksect/__init__.py` not getting included when the package gets built. In fact, checking the contents of the wheel, the only file present in `quicksect/` is `quicksect.cpython-3.8-<platform>.so`. This is the built extension produced by the `cythonize` call in `setup.py`, and it is enough to create the package and allow it to be used through `quicksect.quicksect`, but none of the Python source is included.

### Solutions

The first of these problems can be solved in two ways. The first way is to add `include quicksect/*` to `MANIFEST.in`:

```
# MANIFEST.in
include README.rst
include LICENSE
include quicksectx/*
include quicksect/*
```

This will make sure that `quicksect/quicksect.pyx`, which is currently missing from the sdist archives for v0.3.0 and v0.3.1, gets included in the sdist archive. This allows the package to be installed from source without any issues. However, this solution does not solve the second problem when installing from a built wheel.

A solution that solves both problems is to modify two lines in `setup.py` as follows:

```python
setup(
      [...]
      package_dir={'quicksectx': 'quicksectx', 'quicksect': 'quicksect'},
      packages=['quicksectx', 'quicksect'],
      [...]
)
```

This will include `quicksect` as a package and include its source files, including `quicksect/quicksect.pyx` and `quicksect/__init__.py`, in the sdist and bdist_wheel distributions.

Since including the packages here includes all their files in the sdist and bdist, the lines including them in `MANIFEST.in` are redundant, and can be removed:

```
# MANIFEST.in
include README.rst
include LICENSE
```

If there is some other reason for the redundant lines to be kept in MANIFEST.in that I am not aware of, then performing both solutions would be the way to go, I think.

**Comment by angus-lherrou** [comment]
@jianlins if you agree with this solution then I can open a PR with the changes described above.

**Comment by jianlins** [comment]
just saw this.  It's fixed. Thanks
